# Introduction to Numpy

In [1]:
import numpy as np

In [4]:
print("Numpy version : ",np.__version__)

Numpy version :  1.15.4


In [5]:
#create a simple python list
pythonList = [-5, 4, 0, 3, 9]

#create numpy array from python list
numpyArray = np.array(pythonList)

#display the numpy array
print(numpyArray)

[-5  4  0  3  9]


In [6]:
#another method to display numpy array
numpyArray

array([-5,  4,  0,  3,  9])

**My numpy arrays are just like vectors and we can multiply a vector with a scalor**

In [7]:
numpyArray*2

array([-10,   8,   0,   6,  18])

### Tuples

In [8]:
# create a tuple with first element an integer, 
# second element a float and third element a complex number
myTuple = (5, -8.35, 7-4J)

#create and display the numpy array of this tuple
print(np.array(myTuple))

[ 5.  +0.j -8.35+0.j  7.  -4.j]


### Difference between numpy and python Datastructure

In [11]:
a = [2, 3] # python list
b = np.array([2,3]) #numpy array

a = a*2 # python array will change from [2, 3] to [2, 3, 2, 3]
b = b*2 # numpy is just like a vector and result will be element wise multiplication 

print(a)
print(b)

[2, 3, 2, 3]
[4 6]


# Python Functions

### arange()

<a href='https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.arange.html'>https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.arange.html</a>

In [24]:
np.arange(start=7, stop=20, step=1) # start, stop, step

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
np.arange(7, 20, 3)

array([ 7, 10, 13, 16, 19])

In [19]:
np.arange(7, 10) #start, stop

array([7, 8, 9])

In [20]:
 np.arange(7) #stop is 7 but start is by default 0

array([0, 1, 2, 3, 4, 5, 6])

In [16]:
np.arange(10, 20, 1) -10 +1 #array manupulation

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### linspace()

<a href='https://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html'>https://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html</a>

In [29]:
np.linspace(start = 2, stop = 10, num=9)

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [30]:
np.linspace(2, 10, 9)

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [34]:
myLinSpace = np.linspace(2, 10, 9, retstep=True)

In [35]:
print("My list: ", myLinSpace[0])

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [37]:
print("Step Size : ", myLinSpace[1])

Step Size :  1.0


### zeros()

In [39]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

### ones()

In [40]:
# Vector
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [43]:
# Matrix of size 5 x 4
np.ones((5, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [45]:
# tensor of size 5 x 4 x 3
np.zeros((5, 4, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [46]:
np.zeros(11, dtype='int64')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [47]:
np.zeros(11)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])