# N-dimensional array (ndarray)

In [19]:
import numpy as np

m = [[1,2,3], [4,5,6], [8, 9, 0]]
print(m)

[[1, 2, 3], [4, 5, 6], [8, 9, 0]]


In [20]:
x = np.array(m)
print('x = ')
print(x)
print('Type: ', type(x))
print('Shape: ', x.shape)
print('dtype: ', x.dtype)

x = 
[[1 2 3]
 [4 5 6]
 [8 9 0]]
Type:  <class 'numpy.ndarray'>
Shape:  (3, 3)
dtype:  int32


In [21]:
x = np.array(m, np.float16)
print('x = ')
print(x)
print('Type: ', type(x))
print('Shape: ', x.shape)
print('dtype: ', x.dtype)

x = 
[[1. 2. 3.]
 [4. 5. 6.]
 [8. 9. 0.]]
Type:  <class 'numpy.ndarray'>
Shape:  (3, 3)
dtype:  float16


In [22]:
x = np.array([[1,2,3], [4,5,6], [8, 9, 0]], np.int64)
print('x = ')
print(x)
print('Type: ', type(x))
print('Shape: ', x.shape)
print('dtype: ', x.dtype)

x = 
[[1 2 3]
 [4 5 6]
 [8 9 0]]
Type:  <class 'numpy.ndarray'>
Shape:  (3, 3)
dtype:  int64


In [24]:
#as numpy array is zero based indexed so first element of the matrix is at
#index[0,0]
x[0,0]

1

In [25]:
#last element of the matrix
x[2,2]

0

# Slicing

In [26]:
v = np.array([-2, 3, 4, 6])
v

array([-2,  3,  4,  6])

In [27]:
v[0]

-2

In [28]:
v[0] = 0

In [29]:
v

array([0, 3, 4, 6])

In [30]:
v[-1]

6

In [31]:
v[99]

IndexError: index 99 is out of bounds for axis 0 with size 4

In [43]:
v[765%4]

3

In [42]:
v.size

4

In [45]:
v[765 % v.size]

3

# Two Dimensional Arrays

In [47]:
m = np.arange(35)
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34])

In [ ]:
m.shape = 