# N-dimensional array (ndarray)

In [19]:
import numpy as np

m = [[1,2,3], [4,5,6], [8, 9, 0]]
print(m)

[[1, 2, 3], [4, 5, 6], [8, 9, 0]]


In [20]:
x = np.array(m)
print('x = ')
print(x)
print('Type: ', type(x))
print('Shape: ', x.shape)
print('dtype: ', x.dtype)

x = 
[[1 2 3]
 [4 5 6]
 [8 9 0]]
Type:  <class 'numpy.ndarray'>
Shape:  (3, 3)
dtype:  int32


In [21]:
x = np.array(m, np.float16)
print('x = ')
print(x)
print('Type: ', type(x))
print('Shape: ', x.shape)
print('dtype: ', x.dtype)

x = 
[[1. 2. 3.]
 [4. 5. 6.]
 [8. 9. 0.]]
Type:  <class 'numpy.ndarray'>
Shape:  (3, 3)
dtype:  float16


In [22]:
x = np.array([[1,2,3], [4,5,6], [8, 9, 0]], np.int64)
print('x = ')
print(x)
print('Type: ', type(x))
print('Shape: ', x.shape)
print('dtype: ', x.dtype)

x = 
[[1 2 3]
 [4 5 6]
 [8 9 0]]
Type:  <class 'numpy.ndarray'>
Shape:  (3, 3)
dtype:  int64


In [24]:
#as numpy array is zero based indexed so first element of the matrix is at
x[0,0]

1

In [25]:
x[2,2]

0