# N-dimensional array (ndarray)

In [19]:
import numpy as np

m = [[1,2,3], [4,5,6], [8, 9, 0]]
print(m)

[[1, 2, 3], [4, 5, 6], [8, 9, 0]]


In [20]:
x = np.array(m)
print('x = ')
print(x)
print('Type: ', type(x))
print('Shape: ', x.shape)
print('dtype: ', x.dtype)

x = 
[[1 2 3]
 [4 5 6]
 [8 9 0]]
Type:  <class 'numpy.ndarray'>
Shape:  (3, 3)
dtype:  int32


In [21]:
x = np.array(m, np.float16)
print('x = ')
print(x)
print('Type: ', type(x))
print('Shape: ', x.shape)
print('dtype: ', x.dtype)

x = 
[[1. 2. 3.]
 [4. 5. 6.]
 [8. 9. 0.]]
Type:  <class 'numpy.ndarray'>
Shape:  (3, 3)
dtype:  float16


In [22]:
x = np.array([[1,2,3], [4,5,6], [8, 9, 0]], np.int64)
print('x = ')
print(x)
print('Type: ', type(x))
print('Shape: ', x.shape)
print('dtype: ', x.dtype)

x = 
[[1 2 3]
 [4 5 6]
 [8 9 0]]
Type:  <class 'numpy.ndarray'>
Shape:  (3, 3)
dtype:  int64


In [24]:
#as numpy array is zero based indexed so first element of the matrix is at
#index[0,0]
x[0,0]

1

In [25]:
#last element of the matrix
x[2,2]

0

# Slicing

In [26]:
v = np.array([-2, 3, 4, 6])
v

array([-2,  3,  4,  6])

In [27]:
v[0]

-2

In [28]:
v[0] = 0

In [29]:
v

array([0, 3, 4, 6])

In [30]:
v[-1]

6

In [31]:
v[99]

IndexError: index 99 is out of bounds for axis 0 with size 4

In [43]:
v[765%4]

3

In [42]:
v.size

4

In [45]:
v[765 % v.size]

3

# Two Dimensional Arrays

In [49]:
m = np.arange(48)
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47])

In [50]:
m.shape = (12, 4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47]])

In [51]:
m[0]

array([0, 1, 2, 3])

In [52]:
m[1]

array([4, 5, 6, 7])

In [53]:
m[3]

array([12, 13, 14, 15])

In [54]:
m[-1]

array([44, 45, 46, 47])

In [55]:
m[-2]

array([40, 41, 42, 43])

In [56]:
m[5, 2]

22

In [57]:
m[5][2]

22

# Tensors

In [59]:
t = np.arange(70)
t.shape = (2, 7, 5)
t

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [60]:
t[1]

array([[35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69]])

In [61]:
t[0]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [62]:
t[1,3]

array([50, 51, 52, 53, 54])

In [63]:
t[1][3]

array([50, 51, 52, 53, 54])

In [64]:
t[1][3][2]

52

In [65]:
t[1, 3, 2]

52

In [66]:
t[1][3][2] = 1111

In [67]:
t

array([[[   0,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9],
        [  10,   11,   12,   13,   14],
        [  15,   16,   17,   18,   19],
        [  20,   21,   22,   23,   24],
        [  25,   26,   27,   28,   29],
        [  30,   31,   32,   33,   34]],

       [[  35,   36,   37,   38,   39],
        [  40,   41,   42,   43,   44],
        [  45,   46,   47,   48,   49],
        [  50,   51, 1111,   53,   54],
        [  55,   56,   57,   58,   59],
        [  60,   61,   62,   63,   64],
        [  65,   66,   67,   68,   69]]])

# Boolean Mask Array

In [78]:
v = np.array([-17, -4, 0, 2, 21, 37, 105])
v

array([-17,  -4,   0,   2,  21,  37, 105])

In [79]:
mask = 0 == (v%7) # mask is zero mod 7 mask
mask

array([False, False,  True, False,  True, False,  True])

In [80]:
subArray = v[mask]
subArray

array([  0,  21, 105])

In [81]:
subArray[subArray > 0]

array([ 21, 105])

In [82]:
  subArray

array([  0,  21, 105])

### NumPy Logical Operators

In [89]:
v = np.array([-17, -4, 0, 2, 21, 37, 105])
mode_test = 0 == (v%7)
postive_test = v > 0
print(mode_test)
print(postive_test)

[False False  True False  True False  True]
[False False False  True  True  True  True]


In [92]:
combine_mask = np.logical_and(mode_test, postive_test)
combine_mask

array([False, False, False, False,  True, False,  True])

In [93]:
v[combine_mask]

array([ 21, 105])