# Tensor Operations and Broadcasting Rules

In [1]:
import numpy as np

In [22]:
tensor = np.arange(70)
tensor.shape = (2,7,5)
tensor

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [23]:
# shape
print("Shape: ", tensor.shape)
# number of dimensions
print("Dimensions: ", tensor.ndim)
#size: number of elements
print("Size: ", tensor.size)
#data type for each element
print("Data Type: ", tensor.dtype)

Shape:  (2, 7, 5)
Dimensions:  3
Size:  70
Data Type:  int32


In [24]:
5*tensor-2

array([[[ -2,   3,   8,  13,  18],
        [ 23,  28,  33,  38,  43],
        [ 48,  53,  58,  63,  68],
        [ 73,  78,  83,  88,  93],
        [ 98, 103, 108, 113, 118],
        [123, 128, 133, 138, 143],
        [148, 153, 158, 163, 168]],

       [[173, 178, 183, 188, 193],
        [198, 203, 208, 213, 218],
        [223, 228, 233, 238, 243],
        [248, 253, 258, 263, 268],
        [273, 278, 283, 288, 293],
        [298, 303, 308, 313, 318],
        [323, 328, 333, 338, 343]]])

In [29]:
left_matrix = np.arange(6).reshape((2,3))
right_matrix = np.arange(15).reshape((3,5))

In [30]:
left_matrix

array([[0, 1, 2],
       [3, 4, 5]])

In [31]:
right_matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [32]:
np.inner(left_matrix, right_matrix)

ValueError: shapes (2,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [33]:
a = np.array([1,2,3])
b = np.array([0,1,0])
np.inner(a, b)

2

In [34]:
np.dot(left_matrix, right_matrix)

array([[ 25,  28,  31,  34,  37],
       [ 70,  82,  94, 106, 118]])

In [35]:
tensor

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [36]:
tensor.shape

(2, 7, 5)

In [37]:
tensor.sum()

2415

In [14]:
(69*70)/2

2415.0

In [38]:
tensor.sum(axis = 0)

array([[ 35,  37,  39,  41,  43],
       [ 45,  47,  49,  51,  53],
       [ 55,  57,  59,  61,  63],
       [ 65,  67,  69,  71,  73],
       [ 75,  77,  79,  81,  83],
       [ 85,  87,  89,  91,  93],
       [ 95,  97,  99, 101, 103]])

In [39]:
tensor.sum(axis = 1)

array([[105, 112, 119, 126, 133],
       [350, 357, 364, 371, 378]])

In [40]:
tensor.sum(axis = 2)

array([[ 10,  35,  60,  85, 110, 135, 160],
       [185, 210, 235, 260, 285, 310, 335]])

### Broadcasting Rules

In [41]:
matrix = np.ones(35, dtype='int_').reshape((7, 5)) * 3
matrix

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [47]:
random_matrix = np.random.random((7, 5))

In [48]:
np.set_printoptions(precision=4)
tensor*random_matrix

array([[[ 0.    ,  0.8996,  0.7849,  2.5332,  1.8854],
        [ 1.3962,  2.4372,  2.6497,  3.9867,  4.6219],
        [ 3.8117, 10.4116,  6.0587,  5.9029,  0.8844],
        [ 3.6045,  0.8412,  3.4117,  5.9031, 10.113 ],
        [ 7.7457,  4.6837,  1.2549,  8.6574,  7.0656],
        [24.8011,  0.7272, 14.3732, 15.7662, 18.7781],
        [12.8297, 26.0253, 21.7196, 26.3427,  3.8355]],

       [[23.1001, 32.3838, 14.52  , 32.087 , 18.3827],
        [11.1696, 16.6543, 15.8982, 21.4283, 22.5959],
        [17.1524, 43.5393, 23.7298, 21.7955,  3.0954],
        [12.0149,  2.6812, 10.4357, 17.3813, 28.7423],
        [21.3006, 12.4897,  3.2513, 21.8317, 17.3696],
        [59.5226,  1.706 , 33.0052, 35.4741, 41.4414],
        [27.7977, 55.4087, 45.4753, 54.2819,  7.7838]]])

In [49]:
my_vector = np.arange(5) * 7
my_vector[0] = -1
my_vector

array([-1,  7, 14, 21, 28])

In [50]:
tensor/my_vector

array([[[ -0.    ,   0.1429,   0.1429,   0.1429,   0.1429],
        [ -5.    ,   0.8571,   0.5   ,   0.381 ,   0.3214],
        [-10.    ,   1.5714,   0.8571,   0.619 ,   0.5   ],
        [-15.    ,   2.2857,   1.2143,   0.8571,   0.6786],
        [-20.    ,   3.    ,   1.5714,   1.0952,   0.8571],
        [-25.    ,   3.7143,   1.9286,   1.3333,   1.0357],
        [-30.    ,   4.4286,   2.2857,   1.5714,   1.2143]],

       [[-35.    ,   5.1429,   2.6429,   1.8095,   1.3929],
        [-40.    ,   5.8571,   3.    ,   2.0476,   1.5714],
        [-45.    ,   6.5714,   3.3571,   2.2857,   1.75  ],
        [-50.    ,   7.2857,   3.7143,   2.5238,   1.9286],
        [-55.    ,   8.    ,   4.0714,   2.7619,   2.1071],
        [-60.    ,   8.7143,   4.4286,   3.    ,   2.2857],
        [-65.    ,   9.4286,   4.7857,   3.2381,   2.4643]]])

In [51]:
 tensor%my_vector

array([[[ 0,  1,  2,  3,  4],
        [ 0,  6,  7,  8,  9],
        [ 0,  4, 12, 13, 14],
        [ 0,  2,  3, 18, 19],
        [ 0,  0,  8,  2, 24],
        [ 0,  5, 13,  7,  1],
        [ 0,  3,  4, 12,  6]],

       [[ 0,  1,  9, 17, 11],
        [ 0,  6,  0,  1, 16],
        [ 0,  4,  5,  6, 21],
        [ 0,  2, 10, 11, 26],
        [ 0,  0,  1, 16,  3],
        [ 0,  5,  6,  0,  8],
        [ 0,  3, 11,  5, 13]]], dtype=int32)